name: tameny
description: "Tameny: A digital healthcare platform connecting patients with hospitals, clinics, and labs."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  intl: ^0.19.0
  mailer: ^6.0.0
  http: ^1.1.0
  flutter_slidable: ^3.0.1
  shimmer: ^3.0.0
  google_generative_ai: ^0.2.2
  flutter_markdown: ^0.6.14
  url_launcher: ^6.2.2
  video_player: ^2.8.1
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/icon/
    - assets/fonts/
    - assets/products/
    - assets/pharmacies/
    - assets/hospitals/
    - assets/Background image.png
    - assets/Doctors.png
    - assets/Hospitals.png
    - assets/Labs and scan centre.png
    - assets/Need a visit.png
    - assets/Online.png
    - assets/Pharmacy.png
    - assets/Reserve.png
    - assets/chatbot.png
    - assets/doctor_avatar.png
    - assets/egyptian_pharmacies_20.json
    - assets/orders and reservation.png
    - assets/reservationand serach.png
    - assets/Emergency Guide logo.png
    - assets/tameny_header_logo.png
    - assets/videos/
    - assets/pdfs/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
    - family: GoiaDisplayVariable
      fonts:
        - asset: assets/GoiaDisplayVariable.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/tameny_icon.png"
